# Generated by Django 3.2.12 on 2022-02-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='photo_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
