# Generated by Django 3.2.12 on 2022-02-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_drink_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='photo_url',
            field=models.CharField(max_length=400),
        ),
    ]
