# Generated by Django 3.2.12 on 2022-02-14 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_drink_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAtShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(choices=[('PYATEROCHKA', 'pyaterochka'), ('LENTA', 'lenta'), ('MAGNIT', 'magnit')], max_length=15)),
                ('price', models.SmallIntegerField()),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.drink')),
            ],
        ),
    ]
