# Generated by Django 3.2.12 on 2022-02-14 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_priceatshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('photo_url', models.CharField(max_length=400)),
                ('bio', models.TextField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=140)),
                ('date', models.DateTimeField()),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.drink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.user')),
            ],
        ),
    ]
